config/routes.rb
Ninety9Cats::Application.routes.draw do
  resources :cats
  resources :cat_rental_requests
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates :name, presence: true
  validates :sex, inclusion: { in: %w(M F),
    message: "select a sex"}
  validates :color, inclusion: { in: %w(black white grey ginger blue tabby) }

  has_many(
    :cat_rental_requests,
    class_name: "CatRentalRequest",
    foreign_key: :cat_id,
    primary_key: :id
  )

  def age
    now = Time.now.utc.to_date
    now.year - self.birth_date.year -
      (birth_date.to_date.change(:year => now.year) > now ? 1 : 0 )
  end

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :status, presence: true
  validates :status, inclusion: { in: ["PENDING", "APPROVED", "DENIED"],
    message: "check value of status" }
  validate :overlapping_approved_requests
  after_initialize :init_status

  belongs_to(
    :cat,
    class_name: "Cat",
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy
  )

  private

  def init_status
    self[:status] ||= "PENDING"
  end

  def overlapping_requests
    CatRentalRequest.all
      .where.not("end_date < #{self.start_date} || start_date > #{self.end_date}")
      .where.not(:cat_id)
  end

  def overlapping_approved_requests
    #one who does not have overlap
    return true unless :status == "APPROVED"
    results = overlapping_requests
      .where(:status => "APPROVED")
    !results.empty?
  end

  def overlapping_pending_requests
    overlapping_requests
      .where(:status => "PENDING")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @cat_rental_request.save
      redirect_to cat_url(id: params[:cat_rental_request][:cat_id])
    else
      render text: "rental request fails", status: :unprocessable_entity
    end
  end

  def new
    @cats = Cat.all
    render :new
  end

  private
  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      render :show
    else
      render text: "cat create fails", status: :unprocessable_entity
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :birth_date, :color, :description, :sex)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/new.html.erb
<title>Rental request!</title>
<form id="form_id" action="<%= cat_rental_requests_url %>" method="post">

  <select id="cat_rental_request_cat_id" name="cat_rental_request[cat_id]">
    <option disabled selected>-- select a cat --</option>
    <% @cats.each do |cat| %>
    <option value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>
  </select>
  <br>

  <label for="cat_rental_request_start_date">Start date:</label>
  <input type="date" name="cat_rental_request[start_date]" id="cat_rental_request_start_date" value="">
  <br>

  <label for="cat_rental_request_end_date">End date:</label>
  <input type="date" name="cat_rental_request[end_date]" id="cat_rental_request_end_date" value="">
  <br>

  <input type="submit" value="Make request">
</form>

app/views/cats/_form.html.erb
<form action="/cats/<%= @cat[:id] %>" method="post">
  <input type="hidden" name="_method" value="<%= @cat.persisted? ? "patch" : "post" %>">

  <label for="cat_name">Name</label>
  <input type="text" name="cat[name]" value="<%= @cat.name %>">
  <br>

  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M" <%= @cat.sex == "M" ? "checked" : "" %> >
  <label for="cat_sex_male">Male</label>
  <br>
  <input type="radio" name="cat[sex]" id="cat_sex_female" value="F" <%= @cat.sex == "F" ? "checked" : "" %> >
  <label for="cat_sex_female">Female</label>
  <br>

  <% colors =  %w(black white grey ginger blue tabby) %>
  <label for="cat_color">Color</label>
  <select id="cat_color" name="cat[color]">
    <%= @cat.persisted? ? "" : "<option disabled selected> -- select an option -- </option>".html_safe %>
    <% colors.each do |color| %>
    <option value="<%= color %>" <%= color == @cat[:color] ? "selected" : ""%>><%= color.capitalize %></option>
    <% end %>
  </select>
  <br>

  <label for="cat_birth_date">Birth_date</label>
  <input id="cat_birth_date" type="date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
  <br>

  <label for="cat_description">Description</label>
  <!-- <input id="cat_description" type="textarea" name="cat[description]" "> -->
  <textarea name="cat_description" rows="8" cols="40"><%= @cat.description %></textarea>
  <br>

  <input type="submit" value="Submit">
  <br>

</form>

app/views/cats/edit.html.erb
<title>Edit cat!</title>
<%= render partial: "form", locals: { cat: @cat } %>

app/views/cats/index.html.erb
<h1>All Cats</h1>
  <ul>
  <% @cats.each do |cat| %>
    <li>
      <a href="<%= "#{ cats_url }/#{ cat[:id] }" %>"><%= cat[:name] %></a>
    </li>
  <% end %>
  </ul>

app/views/cats/new.html.erb
<title>Create cat!</title>
<% @cat = Cat.new %>
<%= render partial: "form", locals: { cat: @cat } %>

app/views/cats/show.html.erb
<h1>Show <%= @cat[:name] %></h1>
  <table>
    <tr>
      <% @cat.attributes.each do |name, value| %>
        <th>
          <%= name %>
        </th>
      <% end %>
    </tr>

    <tr>
      <% @cat.attributes.each do |name, value| %>
        <td>
          <%= value %>
        </td>
      <% end %>
    </tr>

    <br>

    <% @cat.cat_rental_requests.order(:start_date).each do |crr| %>
    <tr>
      <td> <%= crr.start_date %> </td>
      <td> <%= crr.end_date %> </td>
    </tr>
    <% end %>
  </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninety9Cats</title>

</head>
<body>

<%= yield %>

</body>
</html>